mixed_precision: "fp16"
dropout_rate: 0.5
epochs: 50
eval_batch_size: 64
eval_num_workers: 4
expt_dir: "/local-scratch2/GitHub/skin-IAV-prediction_models/diag-iampp/"
logs_dir: "./logs/diag-iampp/"
train_img_dir: "/dev/shm/myramdisk/data_preparation/images/"
val_img_dir: "/dev/shm/myramdisk/data_preparation/images/"
test_img_dir: "/dev/shm/myramdisk/data_preparation/images/"
loss: "focal"
lr: 0.01
metric: "dice_score_mean"
num_classes: 2
pretrained: True
seed: 8888
test_file_list: "/dev/shm/myramdisk/data_preparation/partitions/test.csv"
train_batch_size: 32
train_file_list: "/dev/shm/myramdisk/data_preparation/partitions/train.csv"
train_num_workers: 4
val_file_list: "/dev/shm/myramdisk/data_preparation/partitions/val.csv"