mixed_precision: "fp16"
dropout_rate: 0.5
epochs: 15
eval_batch_size: 64
eval_num_workers: 4
expt_dir: "/path/to/your/experiment/directory/derm7pt/"
logs_dir: "./logs/MTW-FT/derm7pt/"
train_img_dir: "/path/to/processed/data/derm7pt_resized_224/Images/"
val_img_dir: "/path/to/processed/data/derm7pt_resized_224/Images/"
test_img_dir: "/path/to/processed/data/derm7pt_resized_224/Images/"
loss1: "focal"
loss2: "smooth_l1"
lr: 0.001
metric: "dice_score_mean"
num_classes: 2
pretrained: True
seed: 8888
test_file_list: "/path/to/processed/data/derm7pt_resized_224/meta/test.csv"
train_batch_size: 32
train_file_list: "/path/to/processed/data/derm7pt_resized_224/meta/train.csv"
train_num_workers: 4
val_file_list: "/path/to/processed/data/derm7pt_resized_224/meta/val.csv"
weight_file_resnet18: "/path/to/saved/models/resnet18/best_model.pth"
weight_file_mobilenetv2: "/path/to/saved/models/mobilenetv2/best_model.pth"
weight_file_efficientnetb1: "/path/to/saved/models/efficientnetb1/best_model.pth"
